title: Julia Neugarten
url: "https://julianeugarten.github.io"
baseurl: "/julianeugarten"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/julianeugarten/"
 - name: "Publications"
   link: "/publications/"
 - name: "Contact"
   link: "/contact/"
